### PR TITLE
11 update plugin to be compatible to the current backend

### LINKED ISSUE #11: update plugin to be compatible to the current backend

### PR DESCRIPTION
**Pull request by unglaublicherdude**

### CODE REVIEW

**Comment by unglaublicherdude** [comment]
Still Missing: GH Release as zip, tgz

**Comment by lennartdohmann** [comment]
If I see this correctly, is the Resource Owner Password Flow already supported? Can [this](https://github.com/GDATASoftwareAG/wordpress-gdata-antivirus/issues/10) issue be closed?

>

**Review by pstadermann — APPROVED** [review]

**Review by lennartdohmann — APPROVED** [review]

**Comment by unglaublicherdude** [comment]
> If I see this correctly, is the Resource Owner Password Flow already supported? Can [this](https://github.com/GDATASoftwareAG/wordpress-gdata-antivirus/issues/10) issue be closed?
> 

yes

**Pull request merged**
